---
- name: Install Java-17
  hosts: java17
  become: yes
  tasks:
          - name: Install Java-17 packages
            apt:
              name: "openjdk-17-jdk"
              state: present
              update_cache: yes
