---
- name: Install Additional packages
  hosts: vms
  become: yes
  vars_files: vars.yaml
  tasks:
          - name: Install mist packages
            apt:
              name: '{{ item }}'
              state: present
            loop:
              "{{ mist_pkgs }}"