---
- name: Install Nginx
  hosts: nginx
  become: yes
  tasks:
          - name: Install Nginx
            apt:
              name: nginx
              state: present
          - name: Start the Nginx
            service:
              name: nginx
              enabled: yes
              state: started