---
- name: Install postgresql
  hosts: sql
  become: yes
  tasks:
          - name: Install postgresql
            apt:
              name:
                - postgresql
                - postgresql-contrib
                - libpq-dev
                - python3-psycopg2
              state: present
          - name: Start and enable postgresql service
            service:
              name: postgresql
              enabled: true
              state: restarted