---
- name: Install vault from HashiCorp
  hosts: vault
  become: true
  tasks:
          - name: issue
            command:
              cmd: dpkg --configure -a
          
          - name: Install dependency pkgs for VAULT
            apt:
              name:
                - gnupg
                - software-properties-common
              state: present
              update_cache: true

          - name: Install Hasicorp GPG key
            shell:
              wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg > /dev/null

          - name: Display Hashicorp GPG key fingerprint
            command: gpg --no-default-keyring --keyring /usr/share/keyrings/hashicorp-archive-keyring.gpg --fingerprint
            register: key_fingerprint

#          - name: Add Hashicorp repository
 #           vars:
  #            hashicorp_keyring: /usr/share/keyrings/hashicorp-archive-keyring.gpg
   #           hashicorp_repo_url: https://apt.releases.hashicorp.com
    #          hashicorp_repo_file: /etc/apt/sources.list.d/hashicorp.list

          - name: Get distribution codename
            command: lsb_release -cs
            register: distro_codename

          - name: Build Hashicorp repository line
            set_fact:
              hashicorp_repo_line: "deb [signed-by=usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com{{ distro_codename.stdout }} main"

          - name: Create Hashicorp repository file
            file:
              path: /etc/apt/sources.list.d/hashicorp.list
              state: touch

          - name: Add Hashicorp repository to sources list
            lineinfile:
              path: /etc/apt/sources.list.d/hashicorp.list
              line: "{{ hashicorp_repo_line }}"

          - name: issue
            command:
              cmd: dpkg --configure -a

          - name: Install Vault
            apt:
              name: vault
              state: present