---
- name: Install and configure Vault
  hosts: vault
  become: true
  tasks:
    - name: Add Hashicorp repository to sources list
      shell: echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list

    - name: Install Hashicorp GPG key
      shell: wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg > /dev/null

    - name: Update apt package list
      apt:
        update_cache: yes

    - name: issue
      command:
        cmd: dpkg --configure -a

    - name: Install Vault
      apt:
        name: vault
        state: present
